language: node_js
node_js:
- 8.9.0
cache:
  yarn: true
  directories:
  - node_modules
services:
  - xvfb
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: jzEELGCLjtYZ9jbS3GFO8l2px7rjbVDUQjp6JPbf6Se99VHKLuroQVqFwZrpXqx3Ar5jpSTJYp/3zpuEv+xTmU4tp4UfY4xIEY0m7TMVZ0no13ko4hNl2A+PZ67V170/rsT5SwQjMr97noM4aHgrxXgvutB2hZDUpJMRMGZzGUPuXs4SkkHALSbyr5mM/HTGnCH4UYZNPBFuiBO3AS+FHrHK6BadAeI6Fu1Pe1CX4aqa2FuFIqlvSCS9OEzfZQwIZ1sUzgQ+pUcFru+txGreMheo1V/OjDPCwFv8hsA90b7SgmBmODz/bFD2RNlEJBhvHwEBFKnPNSkIt9LJz8BCnPqh38WS7DsDwrI/9L9WPfoxp8m8mKpVshiOWY/tZUVQLlRMXeqe6ef1w4lDEBmCyYE3cEufroJLvtiB7U/kuDxwDaxDOCnDbc2dRvFvD4i79YU7rTofmQnzOR/rrNOjN5vGfLYlxapwuImVh5gWLS/W5WGWbyo+Q2RgQEi2u+8PKFi5/BepYZN7qKkS7Gh/ybJ1WTYhy0GL6U5VRnRmkVQXZMBTf7baF6L5cKAsOyr2BCuQMUwc5dXHTb3naTTeXPug6lQXMb2Lt/pFzsEv7P9fMlXjMccNCloeAJupkC/Gcmnh6iFmJgYN7usRwerijDgvb4L+Mg4q7JzpNIWyA8o=
  - secure: ipp5qbzDoj/wwq3n4PTBIHPO4FX8GiFMjpDZNdx6aTeAhvKbclVQQ2oP+S8wxzKCK4FVGPWHPHJFyoNHxhclydnS5DceNwKPm8+LiT0pJ3xsIchA3ItRF/oW7k0P9UNrsdkra28Vlz0SZ3YxzN6goSU6sQKQ9rt+4O0ON2alM/zMmsFnMvaehW0v0gTmSIsI+suqLYFJ5/c6sHpiIYBkj6rYA3DC6iPM73G5vpuhQGrwnIjVTMj0vBxmi4Dl2uYVhrwFyA35rqNUbbTBsajyJea6CMijJNGoU15VI94Pw80viooebkJUQukiUdlcC4UbvkrIfGL4BG0K4lrOHijXwWN+/Q7+2M+tlRRDviT9VDDCWs9cQ8WG45f2Qp83naimaROtT3HQsdonVmr1Bhu9l1GSRonj/TVSpdGJkZ/R2GHGpeC3tefvoCKffJ6qVYMr3wXvumB8X2EY+uVM9aAZjiGe+V/H9Br0OSERuz6731VCdZMZS42Y2rFVLpwaNhrFjiqDb6hoQuhOKUnwN7ktaV8YG7NcjaJHiD9eqhDMc5qdCy6pirkVrc1xHvPxfFMlmBKipIBoFfEFxg7tzt0OkH9OoM1pNRLxXnXqC78KNHkJTFtXfhlroy60G8huTSJ9hECoZBwLZabVAPrjamxmyq/EwiPTOabe89rVqnFnu+Y=
  - secure: M4qBMwS65lsVBZcpOxNLsIhwoVdRItDwCh9GH5EZyaVjgyCaUGCZGyeMea22NgLgygQEUpVmHi8QgHPDwsjR3vTKuzSRRtCWvUrbNJ45UcUg3q+ugEa7t1mrWBqRsibC/T/D4JOBVFTEBJl7Q34yb4wzVZd2Vmp7E03q+CJYOloL1hrrb+eveOfiO8ZfsphQkXHC2SAI3U8hYH+56Zc3vjzkxUOBQZD1YlhXe1R9LMdtgEO1cVbllTh1BS/X3bkUuPkCmgrLImNkfr4NeZm6VSrpZZs7WE7XWgz8RPNurKwoC68Jfupg7J9gurI3kzE3E8uia5lhFmY4cg3RSWiDClZdISUIRONQRYClKRBuMaGVIlfzfk3tfkug1L6gw4wPTeyjk4pFv1BJKGam42b9lYFaLZlDkijdwUNr9k7xkw19xNHJ5WQX7BKPw4e6cbXT2xXyOHkgdsKg1E+vbAh8fDaD1grhSeJkegHUO3uLR1HUZdeuGJSi7//UzxEv+Hs3Qg6sw7KVmWsKqEh4BCXlCcZVzAL6iPCxyrf9ntLCGVszG5mlroEp+Rh274wAJQvHJpgQPzApaxowFZIHnGqFpxyogcO3/SdEHIAuYUWtkyVxxaQkGPYoAwT+zbhFwlA1dMdgTyLfk8xUU24fdZjeCJ28a/D+dc8HtH/yMZN8IIU=
before_install:
- export DISPLAY=:99.0
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- yarn install
script:
- yarn test
- yarn release:trigger